### PR TITLE
Avoid bug in conda-build 3.28.3

### PR DESCRIPTION
**Pull request by carterbox**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by carterbox** [comment]
This change will be undone whenever the feedstock is rerendered. Hopefully, a fix will be published before you need to do that.

If you are planning to expand immediately to ARM processors, then you will need to ensure that this change is not erased by conda-smithy.

**Comment by xhochy** [comment]
@carterbox Do you have a link to the bug?

**Comment by carterbox** [comment]
https://github.com/conda/conda-build/issues/5136

**Comment by MementoRC** [comment]
@carterbox , @xhochy Thank you. This was a long journey

**Review by MementoRC — APPROVED** [review]

**Pull request merged**
